---
title: "QTM Final Project - Restaurant Data"
author: "Eric Gu, Sergio Eraso, Kristina Trifonova, Jai Arora, Anjanay Nangia"
output: html_document
---
## Part A (15 points). Setting up the Research Question & Preliminary Exploratory Analysis

### 1 (1 point). 

#### Identify your data set. Then, describe in a single paragraph what you want to investigate after carefully reviewing the data set and its codebook. 

We will be using the DOHMH_NYC data set, which is a dataset that includes a mass amount of data on health and safety quality of restaurants and cafes across New York City. After analyzing the multiple variables within the dataset, we are choosing to examine the relationship between the health inspection scores given to New York restaurants and cafes based on the different cuisines the restaurants serve to see if there is any potential bias in how health inspection scores are assigned to restaurants.

#### You will choose two variables to start your investigation.

### 2 (2 points).  

#### First, choose a numerical response variable. This is the outcome (response) of your research interest which must be a numerical vector. Provide your rationale for choosing this variable as your response variable, then print the summary statistics of the variable such as mean, standard deviation, median, minimum, and maximum values. Also, produce an appropriate plot using only this variable.

The response variable that we will be using is SCORE, which consists of numerical scores given to each restaurant with higher scores indicating less sanitary conditions and lower scores indicating safer food preparation. We chose to use SCORE as our response variable so that we can ultimately assess any potential cultural biases in the restaurant regulation industry and see how scores vary by region. It is the most informative numerical variable provided in the data set.

summary(DOHM$SCORE)

ggplot(DOHM, aes(SCORE))+
  geom_histogram()

### 3 (2 points). 

#### Examine the plot, and report any unusual observations. Explain why you find some observations strange or unusual. Then, create a new response variable in your data frame using your original response variable. In doing so, you should exclude all of the unusual observations by converting them into NAs.


There are several restaurants which were given negative scores. A negative score does not have a meaning within the context of the data.

DOHM0 <- subset(DOHM, DOHM$SCORE >= 0 & is.na(DOHM$SCORE) == FALSE)

summary(DOHM0$SCORE)

### 4 (2 points). 

#### Now, choose your second variable, which will serve as the main explanatory variable. This could be either numerical or categorical, and it is the variable used to explain the outcome of the variable mentioned in Question 2. Thus, you should choose a variable that you think will be related with the response variable. Explain why you chose this variable as your main explanatory variable, and print the summary of this variable including a plot.  

The main explanatory variable we will be using is CUISINE, a categorical variable which describes the type of food - based on region - offered by the restaurant. We are interested in learning if restaurant scores/ratings are biased with cuisine type. In other words, we are looking for whether certain cuisines representative of minority groups are disproportionately rated lower than others. 
                  
summary(DOHM0$CUISINE.DESCRIPTION)

ggplot(DOHM0, aes(CUISINE.DESCRIPTION) +
  geom_histogram()

### 5 (1 point). 

#### Similar to what you did in Question 3, report any unusual observations in your explanatory variable. Create a new explanatory variable in your data frame using your original response variable. In doing so, you should exclude all of the unusual observations by converting them into NAs.

DOHM1 <- subset(DOHM0, DOHM0$CUISINE.DESCRIPTION == "Afghan" |
                  DOHM0$CUISINE.DESCRIPTION == "African" |
                  DOHM0$CUISINE.DESCRIPTION == "American" |
                  DOHM0$CUISINE.DESCRIPTION == "Armenian" |
                  DOHM0$CUISINE.DESCRIPTION == "Asian" |
                  DOHM0$CUISINE.DESCRIPTION == "Australian" |
                  DOHM0$CUISINE.DESCRIPTION == "Bangladeshi"|
                  DOHM0$CUISINE.DESCRIPTION =="Brazilian"|
                  DOHM0$CUISINE.DESCRIPTION =="Cajun"|
                  DOHM0$CUISINE.DESCRIPTION =="Caribbean"|
                  DOHM0$CUISINE.DESCRIPTION =="Chilean"|
                  DOHM0$CUISINE.DESCRIPTION =="Chinese"|
                  DOHM0$CUISINE.DESCRIPTION =="Creole"|
                  DOHM0$CUISINE.DESCRIPTION =="Czech"|
                  DOHM0$CUISINE.DESCRIPTION =="Eastern European"|
                  DOHM0$CUISINE.DESCRIPTION =="Egyptian"|
                  DOHM0$CUISINE.DESCRIPTION =="English"|
                  DOHM0$CUISINE.DESCRIPTION =="Ethiopian"|
                  DOHM0$CUISINE.DESCRIPTION =="Filipino"|
                  DOHM0$CUISINE.DESCRIPTION =="French"|
                  DOHM0$CUISINE.DESCRIPTION =="German"|
                  DOHM0$CUISINE.DESCRIPTION =="Greek"|
                  DOHM0$CUISINE.DESCRIPTION =="Indian"|
                  DOHM0$CUISINE.DESCRIPTION =="Indonesian"|
                  DOHM0$CUISINE.DESCRIPTION =="Iranian"|
                  DOHM0$CUISINE.DESCRIPTION =="Irish"|
                  DOHM0$CUISINE.DESCRIPTION =="Italian"|
                  DOHM0$CUISINE.DESCRIPTION =="Japanese"|
                  DOHM0$CUISINE.DESCRIPTION =="Jewish/Kosher"|
                  DOHM0$CUISINE.DESCRIPTION =="Korean"|
                  DOHM0$CUISINE.DESCRIPTION =="Latin (Cuban, Dominican, Puerto Rican, South & Central American)"|
                  DOHM0$CUISINE.DESCRIPTION =="Mediterranean"|
                  DOHM0$CUISINE.DESCRIPTION =="Mexican"|
                  DOHM0$CUISINE.DESCRIPTION =="Middle Eastern"|
                  DOHM0$CUISINE.DESCRIPTION =="Moroccan"|
                  DOHM0$CUISINE.DESCRIPTION =="Pakistani"|
                  DOHM0$CUISINE.DESCRIPTION =="Peruvian"|
                  DOHM0$CUISINE.DESCRIPTION =="Polish"|
                  DOHM0$CUISINE.DESCRIPTION =="Portuguese"|
                  DOHM0$CUISINE.DESCRIPTION =="Russian"|
                  DOHM0$CUISINE.DESCRIPTION =="Scandinavian"|
                  DOHM0$CUISINE.DESCRIPTION =="Spanish"|
                  DOHM0$CUISINE.DESCRIPTION =="Thai"|
                  DOHM0$CUISINE.DESCRIPTION =="Turkish"|
                  DOHM0$CUISINE.DESCRIPTION =="Vietnamese/Cambodian/Malaysia")
                  
summary(DOHM1$CUISINE.DESCRIPTION)

### 6 (3 points). 

#### Describe what you expect to see regarding a relationship between the two variables you chose in Questions 2 and 4. In other words, how do you expect your explanatory variable (i.e., the predictor) is associated with the response variable (i.e., the outcome)? It is important to remember that your response to this question should be similar to your response for Question 1 with more specific predictions involving the two variables. Be sure to explain why you expect such a pattern between the two variables (i.e., the rationale). 

With everything going on in the world right now in terms of discrimination based on race, ethnicity, and culture, it is possible that the health inspection scores given out to restaurants in New York City is biased and impacted by the type of food that restaurants serve. We expect there to be lower scores for cafes and restaurants that serve American food and higher scores for restaurants that serve food from other cultures, assuming that discrimination based on race and culture can also creep into how people view certain cultures in terms of sanitary conditions and health. However, New York City is a very diverse population and is considered the melting pot of the United States, which is why we may not see as much or any discrimination based on cuisine type. This is why we are analyzing these variables to uncover a pattern if there is one. 

### 7 (2 points). 

Produce a simple plot showing the overall relationship between your two variables by placing the explanatory variable on the x-axis and the response variable on the y-axis. Be sure to label both axes and include a title for the plot by using appropriate arguments. 

MIDDLE.EAST <- DOHM0 %>%
  filter(CUISINE.DESCRIPTION == "Afghan" |
           CUISINE.DESCRIPTION == "Armenian"|
           CUISINE.DESCRIPTION =="Egyptian"|
           CUISINE.DESCRIPTION =="Iranian"|
           CUISINE.DESCRIPTION =="Middle Eastern" |
           CUISINE.DESCRIPTION == "Turkish") %>%
  summarise(AVG.SCORE=mean(SCORE))

AFRICAN <- DOHM0 %>% 
  filter(CUISINE.DESCRIPTION == "African" |
           CUISINE.DESCRIPTION =="Ethiopian"|
           CUISINE.DESCRIPTION =="Moroccan") %>%
  summarise(AVG.SCORE=mean(SCORE))

AMERICAN <- DOHM0 %>%
  filter(CUISINE.DESCRIPTION == "American" |
           CUISINE.DESCRIPTION == "Cajun" |
           CUISINE.DESCRIPTION == "Creole") %>%
  summarise(AVG.SCORE=mean(SCORE))

SOUTH.AMERICAN <- DOHM0 %>%
  filter(CUISINE.DESCRIPTION =="Brazilian"|
           CUISINE.DESCRIPTION =="Chilean"|
           CUISINE.DESCRIPTION =="Latin (Cuban, Dominican, Puerto Rican, South & Central American)"|
           CUISINE.DESCRIPTION == "Peruvian") %>%
  summarise(AVG.SCORE=mean(SCORE))

EUROPEAN <- DOHM0 %>%
  filter(CUISINE.DESCRIPTION == "Afghan" |
           CUISINE.DESCRIPTION =="Czech"|
           CUISINE.DESCRIPTION =="Eastern European"|
           CUISINE.DESCRIPTION =="English"|
           CUISINE.DESCRIPTION =="French"|
           CUISINE.DESCRIPTION =="German"|
           CUISINE.DESCRIPTION =="Greek"|
           CUISINE.DESCRIPTION =="Irish"|
           CUISINE.DESCRIPTION =="Italian"|
           CUISINE.DESCRIPTION =="Mediterranean"|
           CUISINE.DESCRIPTION =="Polish"|
           CUISINE.DESCRIPTION =="Portuguese"|
           CUISINE.DESCRIPTION =="Russian"|
           CUISINE.DESCRIPTION =="Scandinavian"|
           CUISINE.DESCRIPTION =="Spanish") %>%
  summarise(AVG.INCOME=mean(SCORE))

SOUTH.ASIAN <- DOHM0 %>%
  filter(CUISINE.DESCRIPTION == "Bangladeshi"|
           CUISINE.DESCRIPTION =="Indian"|
           CUISINE.DESCRIPTION =="Pakistani") %>%
  summarise(AVG.INCOME=mean(SCORE))

EAST.ASIAN <- DOHM0 %>%
  filter(CUISINE.DESCRIPTION =="Chinese"|
           CUISINE.DESCRIPTION =="Japanese"|
           CUISINE.DESCRIPTION =="Korean") %>%
  summarise(AVG.INCOME=mean(SCORE))

SOUTHEAST.ASIAN <- DOHM0 %>%
  filter(CUISINE.DESCRIPTION =="Filipino"|
           CUISINE.DESCRIPTION =="Indonesian"|
           CUISINE.DESCRIPTION =="Thai"|
           CUISINE.DESCRIPTION =="Vietnamese/Cambodian/Malaysia") %>%
  summarise(AVG.INCOME=mean(SCORE))

CENTRAL.AMERICA <- DOHM0 %>%
  filter(CUISINE.DESCRIPTION == "Caribbean"|
           CUISINE.DESCRIPTION == "Mexican") %>%
  summarise(AVG.INCOME=mean(SCORE))

AUSTRALIAN <- DOHM0 %>%
  filter(CUISINE.DESCRIPTION == "Australian") %>%
  summarise(AVG.SCORE=mean(SCORE))

AVG.GLOBAL.SCORES <- c(MIDDLE.EAST[,1], AFRICAN[,1], AMERICAN[,1], SOUTH.AMERICAN[,1], EUROPEAN[,1], SOUTH.ASIAN[,1], EAST.ASIAN[,1], SOUTHEAST.ASIAN[,1], CENTRAL.AMERICA[,1], AUSTRALIAN[,1])
is.numeric(AVG.GLOBAL.SCORES)

GLOBAL.NAMES <- c("MIDDLE EAST", "AFRICAN", "AMERICAN", "SOUTH AMERICAN", "EUROPEAN", "SOUTH ASIAN", "EAST ASIAN", "SOUTHEAST ASIAN", "CENTRAL AMERICAN", "AUSTRALIAN")

GLOBAL.SCORES1 <- data.frame(GLOBAL.NAMES, AVG.GLOBAL.SCORES)

ggplot(GLOBAL.SCORES1, aes(GLOBAL.NAMES, AVG.GLOBAL.SCORES)) +
  xlab("Cuisine region") +
  ylab("Average Score") +
  labs(title = "Relationship between global region of cuisine and average score") +
  geom_point()

### 8 (2 points). 

In plain English, describe the pattern (if any) between the explanatory and the response variables observed in the plot. Did it match your expectation? Why or why not? Explain the outcome.


## Part B (17 points). Data Manipulation & Visualization and Conclusion
1 (2 points). 

In Part A, we observed an overall relationship between two variables. Choose another variable (make sure it's a categorical variable) that can help you investigate this relationship more specifically. This is going to be your secondary explanatory variable. Which variable did you choose? Be sure to provide your rationale for choosing your secondary explanatory variable.

### 2 (2 points). 

Using the two explanatory variables, provide a summary table of the outcome using group_by(), arrange(), and summarize() functions. 

### 3 (2 points). 

Produce an appropriate plot using all three variables. Make sure all of your variables (at least 3) are clearly displayed in the plot. 

### 4 (2 points). 

Describe the plot in plain English. How does this plot differ from the one produced in Part A? Did it match your expectation? Why or why not? Explain the outcome. 

### 5 (2 points). 

Examine your plot again and describe in what ways you can improve it. Here, you can either exclude certain observations/categories, or create a new categorical variable by recoding the categories of the existing variable. Note that you need to clearly justify your actions either way. In other words, why do you think it's necessary to do so, and how do you think your plot will be improved by doing so? 

### 6 (2 points). 

Produce another plot reflecting the modifications you made in Question 5. Describe the plot again. Be sure to specifically describe how this plot is different from the previous one.

### 7 (2 points). 

Choose another explanatory variable (This can be either categorical or numerical). You can either substitute your secondary explanatory variable (i.e., the variable you chose in Question B-1) with this one or add this variable as a fourth variable in your analysis. Explain why you chose this variable to be used with (or instead of) your secondary explanatory variable.

### 8 (2 points). 

Generate another summary table and plot using all of the variables you chose. Describe how this plot looks different from the previous ones.

### 9 (1 point). 

In conclusion, describe what you learned about the outcome using the various explanatory variables you chose. 
